# Importing libraries which we are going to use

In [1]:
import numpy as np
import keras
from keras import backend as K
from keras.models import Sequential
from keras.layers.core import Dense, Flatten
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy
from keras.preprocessing.image import ImageDataGenerator
from keras.layers.normalization import BatchNormalization
from keras.layers.convolutional import *
import pandas as pd
from keras.models import load_model
from keras.preprocessing import image

Using TensorFlow backend.


# Defining the train images path and partial test images path in which we have to add the image to convert it into full path.

In [2]:
train_path = 'DataSet/Train Images'
test_path = 'DataSet\Test Images\\'

In [3]:
train_batches = ImageDataGenerator().flow_from_directory(train_path,target_size = (224,224),classes=['Large','Small'],batch_size = 7)

Found 11998 images belonging to 2 classes.


# Importing keras pretrained model (without top layers) resnet50 which we are going to use as base model.

In [15]:
base_model = keras.applications.resnet50.ResNet50( weights = 'imagenet',include_top = False,input_shape = (224,224,3))

C:\Users\ayush\Anaconda3\lib\site-packages\keras_applications\resnet50.py:265: UserWarning: The output shape of `ResNet50(include_top=False)` has been changed since Keras 2.2.0.
  warnings.warn('The output shape of `ResNet50(include_top=False)` '


# we dont want to train base model.

In [17]:
for layer in base_model.layers:
    layer.trainable = False

# Making keras sequential model by using base model layer as its lower layer and two fully connected dense layer as its top layer which are trainable.

In [18]:
model = Sequential()
model.add(base_model)
model.add(Flatten())
model.add(Dense(1000,activation = 'relu'))
model.add(Dense(2,activation = 'sigmoid'))
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
resnet50 (Model)             (None, 7, 7, 2048)        23587712  
_________________________________________________________________
flatten_2 (Flatten)          (None, 100352)            0         
_________________________________________________________________
dense_1 (Dense)              (None, 1000)              100353000 
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 2002      
Total params: 123,942,714
Trainable params: 100,355,002
Non-trainable params: 23,587,712
_________________________________________________________________
None


# Compile and train the model on epoch = 5 

In [19]:
model.compile(optimizer=Adam(),
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [22]:
history = model.fit_generator(train_batches,
                              epochs=5,
                              steps_per_epoch = 1714,
                             )

Instructions for updating:
Use tf.cast instead.
Epoch 1/5
1714/1714 [==============================] - 4649s 3s/step - loss: 1.7599 - acc: 0.8883
Epoch 2/5
1714/1714 [==============================] - 2875s 2s/step - loss: 0.7455 - acc: 0.9532
Epoch 3/5
1714/1714 [==============================] - 2868s 2s/step - loss: 0.8425 - acc: 0.9470
Epoch 4/5
1714/1714 [==============================] - 2860s 2s/step - loss: 0.6910 - acc: 0.9567
Epoch 5/5
1714/1714 [==============================] - 2860s 2s/step - loss: 0.7588 - acc: 0.9525


# saving the model for future use

In [23]:
model.save('lunar.h5')
print("lunar.h5 was saved")

lunar.h5 was saved


# Reading the csv file as dataframe to get the name of images 

In [70]:
names = pd.read_csv('DataSet/test.csv',dtype = {'Image_file':str, 'Class':str})

# Defining a function predict which takes the full path of image as argument and return the predicted class label

In [101]:
def predict(img_path):
    test_image = image.load_img(img_path, target_size=(224, 224))
    test_image = image.img_to_array(test_image)
    test_image = np.expand_dims(test_image, axis=0)
    result = model.predict(test_image, batch_size=1)
    print(result)
    if(result[0][1]==0):
        return "Large"
    else:
        return "Small"

    
    

# we are changing the class value (in front of its image name) according to the predicted value 

In [103]:

for i in range(len(names)):
    image_path = test_path + names.iloc[i][0]
    label = predict(image_path)
    names.at[i,'Class'] = label

DataSet\Test Images\lg 988 (1).png
[[0. 1.]]
DataSet\Test Images\lg 988 (10).png
[[1. 1.]]
DataSet\Test Images\lg 988 (100).png
[[1. 0.]]
DataSet\Test Images\lg 988 (101).png
[[0. 1.]]
DataSet\Test Images\lg 988 (102).png
[[0. 1.]]
DataSet\Test Images\lg 988 (103).png
[[0. 1.]]
DataSet\Test Images\lg 988 (104).png
[[1. 0.]]
DataSet\Test Images\lg 988 (105).png
[[1. 0.]]
DataSet\Test Images\lg 988 (106).png
[[0. 1.]]
DataSet\Test Images\lg 988 (107).png
[[0. 1.]]
DataSet\Test Images\lg 988 (108).png
[[0. 1.]]
DataSet\Test Images\lg 988 (109).png
[[1. 0.]]
DataSet\Test Images\lg 988 (11).png
[[0. 1.]]
DataSet\Test Images\lg 988 (110).png
[[0. 1.]]
DataSet\Test Images\lg 988 (111).png
[[1. 0.]]
DataSet\Test Images\lg 988 (112).png
[[0. 1.]]
DataSet\Test Images\lg 988 (113).png
[[0. 1.]]
DataSet\Test Images\lg 988 (114).png
[[0. 1.]]
DataSet\Test Images\lg 988 (115).png
[[0. 1.]]
DataSet\Test Images\lg 988 (116).png
[[0. 1.]]
DataSet\Test Images\lg 988 (117).png
[[0. 1.]]
DataSet\Test Imag

[[0. 1.]]
DataSet\Test Images\lg 988 (257).png
[[1. 1.]]
DataSet\Test Images\lg 988 (258).png
[[0. 1.]]
DataSet\Test Images\lg 988 (259).png
[[0. 1.]]
DataSet\Test Images\lg 988 (26).png
[[0. 1.]]
DataSet\Test Images\lg 988 (260).png
[[0. 1.]]
DataSet\Test Images\lg 988 (261).png
[[0. 1.]]
DataSet\Test Images\lg 988 (262).png
[[0. 1.]]
DataSet\Test Images\lg 988 (263).png
[[0. 1.]]
DataSet\Test Images\lg 988 (264).png
[[1. 0.]]
DataSet\Test Images\lg 988 (265).png
[[0. 1.]]
DataSet\Test Images\lg 988 (266).png
[[1. 0.]]
DataSet\Test Images\lg 988 (267).png
[[0. 1.]]
DataSet\Test Images\lg 988 (268).png
[[0. 1.]]
DataSet\Test Images\lg 988 (269).png
[[1. 0.]]
DataSet\Test Images\lg 988 (27).png
[[0. 1.]]
DataSet\Test Images\lg 988 (270).png
[[0. 1.]]
DataSet\Test Images\lg 988 (271).png
[[0. 1.]]
DataSet\Test Images\lg 988 (272).png
[[0. 1.]]
DataSet\Test Images\lg 988 (273).png
[[0. 1.]]
DataSet\Test Images\lg 988 (274).png
[[1. 1.]]
DataSet\Test Images\lg 988 (275).png
[[0. 1.]]
DataS

[[0. 1.]]
DataSet\Test Images\lg 988 (67).png
[[0. 1.]]
DataSet\Test Images\lg 988 (68).png
[[1. 0.]]
DataSet\Test Images\lg 988 (69).png
[[0. 1.]]
DataSet\Test Images\lg 988 (7).png
[[0. 1.]]
DataSet\Test Images\lg 988 (70).png
[[0. 1.]]
DataSet\Test Images\lg 988 (71).png
[[0. 1.]]
DataSet\Test Images\lg 988 (72).png
[[0. 1.]]
DataSet\Test Images\lg 988 (73).png
[[0. 1.]]
DataSet\Test Images\lg 988 (74).png
[[1. 1.]]
DataSet\Test Images\lg 988 (75).png
[[1. 0.]]
DataSet\Test Images\lg 988 (76).png
[[0. 1.]]
DataSet\Test Images\lg 988 (77).png
[[0. 1.]]
DataSet\Test Images\lg 988 (78).png
[[0. 1.]]
DataSet\Test Images\lg 988 (79).png
[[0. 1.]]
DataSet\Test Images\lg 988 (8).png
[[0. 1.]]
DataSet\Test Images\lg 988 (80).png
[[0. 1.]]
DataSet\Test Images\lg 988 (81).png
[[1. 0.]]
DataSet\Test Images\lg 988 (82).png
[[1. 1.]]
DataSet\Test Images\lg 988 (83).png
[[0. 1.]]
DataSet\Test Images\lg 988 (84).png
[[0. 1.]]
DataSet\Test Images\lg 988 (85).png
[[0. 1.]]
DataSet\Test Images\lg 988

[[0. 1.]]
DataSet\Test Images\lg167 (66).png
[[0. 1.]]
DataSet\Test Images\lg167 (67).png
[[0. 1.]]
DataSet\Test Images\lg167 (68).png
[[0. 1.]]
DataSet\Test Images\lg167 (69).png
[[0. 1.]]
DataSet\Test Images\lg167 (7).png
[[0. 1.]]
DataSet\Test Images\lg167 (70).png
[[0. 1.]]
DataSet\Test Images\lg167 (71).png
[[1. 0.]]
DataSet\Test Images\lg167 (72).png
[[0. 1.]]
DataSet\Test Images\lg167 (73).png
[[0. 1.]]
DataSet\Test Images\lg167 (74).png
[[0. 1.]]
DataSet\Test Images\lg167 (75).png
[[0. 1.]]
DataSet\Test Images\lg167 (76).png
[[0. 1.]]
DataSet\Test Images\lg167 (77).png
[[0. 1.]]
DataSet\Test Images\lg167 (78).png
[[1. 1.]]
DataSet\Test Images\lg167 (79).png
[[0. 1.]]
DataSet\Test Images\lg167 (8).png
[[1. 0.]]
DataSet\Test Images\lg167 (80).png
[[1. 1.]]
DataSet\Test Images\lg167 (81).png
[[1. 0.]]
DataSet\Test Images\lg167 (82).png
[[1. 0.]]
DataSet\Test Images\lg167 (83).png
[[1. 0.]]
DataSet\Test Images\lg167 (84).png
[[0. 1.]]
DataSet\Test Images\lg167 (85).png
[[0. 1.]]
Da

[[1. 0.]]
DataSet\Test Images\lg168 (226).png
[[0. 1.]]
DataSet\Test Images\lg168 (227).png
[[0. 1.]]
DataSet\Test Images\lg168 (228).png
[[0. 1.]]
DataSet\Test Images\lg168 (229).png
[[1. 1.]]
DataSet\Test Images\lg168 (23).png
[[0. 1.]]
DataSet\Test Images\lg168 (230).png
[[0. 1.]]
DataSet\Test Images\lg168 (231).png
[[0. 1.]]
DataSet\Test Images\lg168 (232).png
[[0. 1.]]
DataSet\Test Images\lg168 (233).png
[[0. 1.]]
DataSet\Test Images\lg168 (234).png
[[0. 1.]]
DataSet\Test Images\lg168 (235).png
[[0. 1.]]
DataSet\Test Images\lg168 (236).png
[[0. 1.]]
DataSet\Test Images\lg168 (237).png
[[0. 1.]]
DataSet\Test Images\lg168 (238).png
[[0. 1.]]
DataSet\Test Images\lg168 (239).png
[[0. 1.]]
DataSet\Test Images\lg168 (24).png
[[0. 1.]]
DataSet\Test Images\lg168 (240).png
[[0. 1.]]
DataSet\Test Images\lg168 (241).png
[[0. 1.]]
DataSet\Test Images\lg168 (242).png
[[1. 0.]]
DataSet\Test Images\lg168 (243).png
[[0. 1.]]
DataSet\Test Images\lg168 (244).png
[[0. 1.]]
DataSet\Test Images\lg168 

[[0. 1.]]
DataSet\Test Images\lg168 (388).png
[[0. 1.]]
DataSet\Test Images\lg168 (389).png
[[1. 0.]]
DataSet\Test Images\lg168 (39).png
[[0. 1.]]
DataSet\Test Images\lg168 (390).png
[[0. 1.]]
DataSet\Test Images\lg168 (391).png
[[0. 1.]]
DataSet\Test Images\lg168 (392).png
[[0. 1.]]
DataSet\Test Images\lg168 (393).png
[[0. 1.]]
DataSet\Test Images\lg168 (394).png
[[0. 1.]]
DataSet\Test Images\lg168 (395).png
[[0. 1.]]
DataSet\Test Images\lg168 (396).png
[[0. 1.]]
DataSet\Test Images\lg168 (397).png
[[0. 1.]]
DataSet\Test Images\lg168 (398).png
[[0. 1.]]
DataSet\Test Images\lg168 (399).png
[[0. 1.]]
DataSet\Test Images\lg168 (4).png
[[0. 1.]]
DataSet\Test Images\lg168 (40).png
[[0. 1.]]
DataSet\Test Images\lg168 (400).png
[[0. 1.]]
DataSet\Test Images\lg168 (401).png
[[0. 1.]]
DataSet\Test Images\lg168 (402).png
[[0.9998976 1.       ]]
DataSet\Test Images\lg168 (403).png
[[0. 1.]]
DataSet\Test Images\lg168 (404).png
[[0. 1.]]
DataSet\Test Images\lg168 (405).png
[[0. 1.]]
DataSet\Test I

[[0. 1.]]
DataSet\Test Images\lg169 (160).png
[[0. 1.]]
DataSet\Test Images\lg169 (161).png
[[0. 1.]]
DataSet\Test Images\lg169 (162).png
[[1. 1.]]
DataSet\Test Images\lg169 (163).png
[[0. 1.]]
DataSet\Test Images\lg169 (164).png
[[0. 1.]]
DataSet\Test Images\lg169 (165).png
[[0. 1.]]
DataSet\Test Images\lg169 (166).png
[[0. 1.]]
DataSet\Test Images\lg169 (167).png
[[0. 1.]]
DataSet\Test Images\lg169 (168).png
[[0. 1.]]
DataSet\Test Images\lg169 (169).png
[[0.9999999 1.       ]]
DataSet\Test Images\lg169 (17).png
[[1. 1.]]
DataSet\Test Images\lg169 (170).png
[[0. 1.]]
DataSet\Test Images\lg169 (171).png
[[0. 1.]]
DataSet\Test Images\lg169 (172).png
[[0. 1.]]
DataSet\Test Images\lg169 (173).png
[[1. 0.]]
DataSet\Test Images\lg169 (174).png
[[0. 1.]]
DataSet\Test Images\lg169 (175).png
[[0. 1.]]
DataSet\Test Images\lg169 (176).png
[[0. 1.]]
DataSet\Test Images\lg169 (177).png
[[1.         0.99999726]]
DataSet\Test Images\lg169 (178).png
[[0. 1.]]
DataSet\Test Images\lg169 (179).png
[[0. 

[[0. 1.]]
DataSet\Test Images\lg169 (79).png
[[0. 1.]]
DataSet\Test Images\lg169 (8).png
[[0. 1.]]
DataSet\Test Images\lg169 (80).png
[[0. 1.]]
DataSet\Test Images\lg169 (81).png
[[0. 1.]]
DataSet\Test Images\lg169 (82).png
[[0. 1.]]
DataSet\Test Images\lg169 (83).png
[[0. 1.]]
DataSet\Test Images\lg169 (84).png
[[1. 0.]]
DataSet\Test Images\lg169 (85).png
[[1. 0.]]
DataSet\Test Images\lg169 (86).png
[[0. 1.]]
DataSet\Test Images\lg169 (87).png
[[0. 1.]]
DataSet\Test Images\lg169 (88).png
[[0. 1.]]
DataSet\Test Images\lg169 (89).png
[[0. 1.]]
DataSet\Test Images\lg169 (9).png
[[0. 1.]]
DataSet\Test Images\lg169 (90).png
[[0. 1.]]
DataSet\Test Images\lg169 (91).png
[[0. 1.]]
DataSet\Test Images\lg169 (92).png
[[0. 1.]]
DataSet\Test Images\lg169 (93).png
[[0. 1.]]
DataSet\Test Images\lg169 (94).png
[[1. 0.]]
DataSet\Test Images\lg169 (95).png
[[0. 1.]]
DataSet\Test Images\lg169 (96).png
[[0. 1.]]
DataSet\Test Images\lg169 (97).png
[[0. 1.]]
DataSet\Test Images\lg169 (98).png
[[0. 1.]]
Da

[[0. 1.]]
DataSet\Test Images\lg171 (240).png
[[0. 1.]]
DataSet\Test Images\lg171 (241).png
[[0. 1.]]
DataSet\Test Images\lg171 (242).png
[[0. 1.]]
DataSet\Test Images\lg171 (243).png
[[0. 1.]]
DataSet\Test Images\lg171 (244).png
[[1. 0.]]
DataSet\Test Images\lg171 (245).png
[[0. 1.]]
DataSet\Test Images\lg171 (246).png
[[1. 0.]]
DataSet\Test Images\lg171 (247).png
[[0. 1.]]
DataSet\Test Images\lg171 (248).png
[[1. 1.]]
DataSet\Test Images\lg171 (249).png
[[0. 1.]]
DataSet\Test Images\lg171 (25).png
[[1. 0.]]
DataSet\Test Images\lg171 (250).png
[[1. 0.]]
DataSet\Test Images\lg171 (251).png
[[0. 1.]]
DataSet\Test Images\lg171 (252).png
[[0. 1.]]
DataSet\Test Images\lg171 (253).png
[[0. 1.]]
DataSet\Test Images\lg171 (254).png
[[0. 1.]]
DataSet\Test Images\lg171 (255).png
[[0. 1.]]
DataSet\Test Images\lg171 (256).png
[[0. 1.]]
DataSet\Test Images\lg171 (257).png
[[0. 1.]]
DataSet\Test Images\lg171 (258).png
[[0. 1.]]
DataSet\Test Images\lg171 (259).png
[[0. 1.]]
DataSet\Test Images\lg171

[[0. 1.]]
DataSet\Test Images\lg171 (40).png
[[0. 1.]]
DataSet\Test Images\lg171 (400).png
[[0. 1.]]
DataSet\Test Images\lg171 (401).png
[[0. 1.]]
DataSet\Test Images\lg171 (402).png
[[0. 1.]]
DataSet\Test Images\lg171 (403).png
[[0. 1.]]
DataSet\Test Images\lg171 (404).png
[[0. 1.]]
DataSet\Test Images\lg171 (405).png
[[0. 1.]]
DataSet\Test Images\lg171 (406).png
[[1. 0.]]
DataSet\Test Images\lg171 (407).png
[[0. 1.]]
DataSet\Test Images\lg171 (408).png
[[0. 1.]]
DataSet\Test Images\lg171 (409).png
[[0. 1.]]
DataSet\Test Images\lg171 (41).png
[[0. 1.]]
DataSet\Test Images\lg171 (410).png
[[1. 0.]]
DataSet\Test Images\lg171 (411).png
[[0. 1.]]
DataSet\Test Images\lg171 (412).png
[[0. 1.]]
DataSet\Test Images\lg171 (413).png
[[0. 1.]]
DataSet\Test Images\lg171 (414).png
[[0. 1.]]
DataSet\Test Images\lg171 (415).png
[[0. 1.]]
DataSet\Test Images\lg171 (416).png
[[0. 1.]]
DataSet\Test Images\lg171 (417).png
[[0. 1.]]
DataSet\Test Images\lg171 (418).png
[[0. 1.]]
DataSet\Test Images\lg171 

[[0. 1.]]
DataSet\Test Images\lg171 (95).png
[[0. 1.]]
DataSet\Test Images\lg171 (96).png
[[0. 1.]]
DataSet\Test Images\lg171 (97).png
[[0. 1.]]
DataSet\Test Images\lg171 (98).png
[[0. 1.]]
DataSet\Test Images\lg171 (99).png
[[0. 1.]]
DataSet\Test Images\lgl 10 (1).png
[[0. 1.]]
DataSet\Test Images\lgl 10 (10).png
[[0. 1.]]
DataSet\Test Images\lgl 10 (100).png
[[0. 1.]]
DataSet\Test Images\lgl 10 (101).png
[[0. 1.]]
DataSet\Test Images\lgl 10 (102).png
[[1. 0.]]
DataSet\Test Images\lgl 10 (103).png
[[0. 1.]]
DataSet\Test Images\lgl 10 (104).png
[[0. 1.]]
DataSet\Test Images\lgl 10 (105).png
[[0. 1.]]
DataSet\Test Images\lgl 10 (106).png
[[1. 1.]]
DataSet\Test Images\lgl 10 (107).png
[[0. 1.]]
DataSet\Test Images\lgl 10 (108).png
[[0. 1.]]
DataSet\Test Images\lgl 10 (109).png
[[0. 1.]]
DataSet\Test Images\lgl 10 (11).png
[[0. 1.]]
DataSet\Test Images\lgl 10 (110).png
[[0. 1.]]
DataSet\Test Images\lgl 10 (111).png
[[0. 1.]]
DataSet\Test Images\lgl 10 (112).png
[[0. 1.]]
DataSet\Test Imag

[[0. 1.]]
DataSet\Test Images\lgl125 (146).png
[[0. 1.]]
DataSet\Test Images\lgl125 (147).png
[[0. 1.]]
DataSet\Test Images\lgl125 (148).png
[[0. 1.]]
DataSet\Test Images\lgl125 (149).png
[[0. 1.]]
DataSet\Test Images\lgl125 (15).png
[[0. 1.]]
DataSet\Test Images\lgl125 (150).png
[[0. 1.]]
DataSet\Test Images\lgl125 (151).png
[[0. 1.]]
DataSet\Test Images\lgl125 (152).png
[[1. 1.]]
DataSet\Test Images\lgl125 (153).png
[[0. 1.]]
DataSet\Test Images\lgl125 (154).png
[[1. 0.]]
DataSet\Test Images\lgl125 (155).png
[[0. 1.]]
DataSet\Test Images\lgl125 (156).png
[[1. 0.]]
DataSet\Test Images\lgl125 (157).png
[[0. 1.]]
DataSet\Test Images\lgl125 (158).png
[[1. 0.]]
DataSet\Test Images\lgl125 (159).png
[[0. 1.]]
DataSet\Test Images\lgl125 (16).png
[[0. 1.]]
DataSet\Test Images\lgl125 (160).png
[[0. 1.]]
DataSet\Test Images\lgl125 (161).png
[[0. 1.]]
DataSet\Test Images\lgl125 (162).png
[[0. 1.]]
DataSet\Test Images\lgl125 (163).png
[[0. 1.]]
DataSet\Test Images\lgl125 (164).png
[[0. 1.]]
DataS

[[0. 1.]]
DataSet\Test Images\lgl125 (302).png
[[0. 1.]]
DataSet\Test Images\lgl125 (303).png
[[0. 1.]]
DataSet\Test Images\lgl125 (304).png
[[1. 0.]]
DataSet\Test Images\lgl125 (305).png
[[0. 1.]]
DataSet\Test Images\lgl125 (306).png
[[0. 1.]]
DataSet\Test Images\lgl125 (307).png
[[0. 1.]]
DataSet\Test Images\lgl125 (308).png
[[0. 1.]]
DataSet\Test Images\lgl125 (309).png
[[0. 1.]]
DataSet\Test Images\lgl125 (31).png
[[0. 1.]]
DataSet\Test Images\lgl125 (310).png
[[0. 1.]]
DataSet\Test Images\lgl125 (311).png
[[0. 1.]]
DataSet\Test Images\lgl125 (312).png
[[1. 0.]]
DataSet\Test Images\lgl125 (313).png
[[1. 0.]]
DataSet\Test Images\lgl125 (314).png
[[0. 1.]]
DataSet\Test Images\lgl125 (315).png
[[0. 1.]]
DataSet\Test Images\lgl125 (316).png
[[1. 1.]]
DataSet\Test Images\lgl125 (317).png
[[0. 1.]]
DataSet\Test Images\lgl125 (318).png
[[1. 0.]]
DataSet\Test Images\lgl125 (319).png
[[0. 1.]]
DataSet\Test Images\lgl125 (32).png
[[0. 1.]]
DataSet\Test Images\lgl125 (320).png
[[1. 0.]]
DataS

[[0. 1.]]
DataSet\Test Images\lgl125 (460).png
[[0. 1.]]
DataSet\Test Images\lgl125 (461).png
[[0. 1.]]
DataSet\Test Images\lgl125 (462).png
[[0. 1.]]
DataSet\Test Images\lgl125 (463).png
[[0. 1.]]
DataSet\Test Images\lgl125 (464).png
[[0. 1.]]
DataSet\Test Images\lgl125 (465).png
[[0. 1.]]
DataSet\Test Images\lgl125 (466).png
[[0. 1.]]
DataSet\Test Images\lgl125 (467).png
[[0. 1.]]
DataSet\Test Images\lgl125 (468).png
[[0. 1.]]
DataSet\Test Images\lgl125 (469).png
[[0. 1.]]
DataSet\Test Images\lgl125 (47).png
[[0. 1.]]
DataSet\Test Images\lgl125 (470).png
[[0. 1.]]
DataSet\Test Images\lgl125 (471).png
[[0. 1.]]
DataSet\Test Images\lgl125 (472).png
[[1. 1.]]
DataSet\Test Images\lgl125 (473).png
[[0. 1.]]
DataSet\Test Images\lgl125 (474).png
[[1. 0.]]
DataSet\Test Images\lgl125 (475).png
[[0. 1.]]
DataSet\Test Images\lgl125 (476).png
[[1. 0.]]
DataSet\Test Images\lgl125 (477).png
[[0. 1.]]
DataSet\Test Images\lgl125 (478).png
[[0. 1.]]
DataSet\Test Images\lgl125 (479).png
[[0. 1.]]
Data

[[0. 1.]]
DataSet\Test Images\lgl30 (24).png
[[1. 0.]]
DataSet\Test Images\lgl30 (25).png
[[0. 1.]]
DataSet\Test Images\lgl30 (26).png
[[0. 1.]]
DataSet\Test Images\lgl30 (27).png
[[1. 0.]]
DataSet\Test Images\lgl30 (28).png
[[1. 0.]]
DataSet\Test Images\lgl30 (29).png
[[1. 1.]]
DataSet\Test Images\lgl30 (3).png
[[0. 1.]]
DataSet\Test Images\lgl30 (30).png
[[0. 1.]]
DataSet\Test Images\lgl30 (31).png
[[0. 1.]]
DataSet\Test Images\lgl30 (32).png
[[0. 1.]]
DataSet\Test Images\lgl30 (33).png
[[0. 1.]]
DataSet\Test Images\lgl30 (34).png
[[0. 1.]]
DataSet\Test Images\lgl30 (35).png
[[0. 1.]]
DataSet\Test Images\lgl30 (36).png
[[0. 1.]]
DataSet\Test Images\lgl30 (37).png
[[0. 1.]]
DataSet\Test Images\lgl30 (38).png
[[0. 1.]]
DataSet\Test Images\lgl30 (39).png
[[0. 1.]]
DataSet\Test Images\lgl30 (4).png
[[0. 1.]]
DataSet\Test Images\lgl30 (40).png
[[0. 1.]]
DataSet\Test Images\lgl30 (41).png
[[0. 1.]]
DataSet\Test Images\lgl30 (42).png
[[0. 1.]]
DataSet\Test Images\lgl30 (43).png
[[0. 1.]]
Da

[[0. 1.]]
DataSet\Test Images\lgl305 (185).png
[[0. 1.]]
DataSet\Test Images\lgl305 (186).png
[[0. 1.]]
DataSet\Test Images\lgl305 (187).png
[[0. 1.]]
DataSet\Test Images\lgl305 (188).png
[[0. 1.]]
DataSet\Test Images\lgl305 (189).png
[[0. 1.]]
DataSet\Test Images\lgl305 (19).png
[[0. 1.]]
DataSet\Test Images\lgl305 (190).png
[[1. 0.]]
DataSet\Test Images\lgl305 (191).png
[[0. 1.]]
DataSet\Test Images\lgl305 (192).png
[[1. 0.]]
DataSet\Test Images\lgl305 (193).png
[[0. 1.]]
DataSet\Test Images\lgl305 (194).png
[[1. 1.]]
DataSet\Test Images\lgl305 (195).png
[[0. 1.]]
DataSet\Test Images\lgl305 (196).png
[[1. 0.]]
DataSet\Test Images\lgl305 (197).png
[[0. 1.]]
DataSet\Test Images\lgl305 (198).png
[[1. 0.]]
DataSet\Test Images\lgl305 (199).png
[[0. 1.]]
DataSet\Test Images\lgl305 (2).png
[[0. 1.]]
DataSet\Test Images\lgl305 (20).png
[[0. 1.]]
DataSet\Test Images\lgl305 (200).png
[[0. 1.]]
DataSet\Test Images\lgl305 (201).png
[[0. 1.]]
DataSet\Test Images\lgl305 (202).png
[[0. 1.]]
DataSet

[[0. 1.]]
DataSet\Test Images\lgl60 (1).png
[[0. 1.]]
DataSet\Test Images\lgl60 (10).png
[[0. 1.]]
DataSet\Test Images\lgl60 (100).png
[[0. 1.]]
DataSet\Test Images\lgl60 (101).png
[[0. 1.]]
DataSet\Test Images\lgl60 (102).png
[[0. 1.]]
DataSet\Test Images\lgl60 (103).png
[[0. 1.]]
DataSet\Test Images\lgl60 (104).png
[[0. 1.]]
DataSet\Test Images\lgl60 (105).png
[[0. 1.]]
DataSet\Test Images\lgl60 (106).png
[[0. 1.]]
DataSet\Test Images\lgl60 (107).png
[[0. 1.]]
DataSet\Test Images\lgl60 (108).png
[[0. 1.]]
DataSet\Test Images\lgl60 (109).png
[[1. 0.]]
DataSet\Test Images\lgl60 (11).png
[[1. 0.]]
DataSet\Test Images\lgl60 (110).png
[[0. 1.]]
DataSet\Test Images\lgl60 (111).png
[[0. 1.]]
DataSet\Test Images\lgl60 (112).png
[[1. 0.]]
DataSet\Test Images\lgl60 (113).png
[[0. 1.]]
DataSet\Test Images\lgl60 (114).png
[[0. 1.]]
DataSet\Test Images\lgl60 (115).png
[[1. 0.]]
DataSet\Test Images\lgl60 (116).png
[[0. 1.]]
DataSet\Test Images\lgl60 (117).png
[[0. 1.]]
DataSet\Test Images\lgl60 (1

[[0. 1.]]
DataSet\Test Images\lgl60 (260).png
[[0. 1.]]
DataSet\Test Images\lgl60 (261).png
[[1. 1.]]
DataSet\Test Images\lgl60 (262).png
[[0. 1.]]
DataSet\Test Images\lgl60 (263).png
[[1. 0.]]
DataSet\Test Images\lgl60 (264).png
[[0. 1.]]
DataSet\Test Images\lgl60 (265).png
[[1.0000000e+00 1.7605473e-29]]
DataSet\Test Images\lgl60 (266).png
[[1. 0.]]
DataSet\Test Images\lgl60 (267).png
[[0. 1.]]
DataSet\Test Images\lgl60 (268).png
[[0. 1.]]
DataSet\Test Images\lgl60 (269).png
[[0. 1.]]
DataSet\Test Images\lgl60 (27).png
[[0. 1.]]
DataSet\Test Images\lgl60 (270).png
[[0. 1.]]
DataSet\Test Images\lgl60 (271).png
[[1. 1.]]
DataSet\Test Images\lgl60 (272).png
[[0. 1.]]
DataSet\Test Images\lgl60 (273).png
[[0. 1.]]
DataSet\Test Images\lgl60 (274).png
[[0. 1.]]
DataSet\Test Images\lgl60 (275).png
[[0. 1.]]
DataSet\Test Images\lgl60 (276).png
[[0. 1.]]
DataSet\Test Images\lgl60 (277).png
[[0. 1.]]
DataSet\Test Images\lgl60 (278).png
[[0. 1.]]
DataSet\Test Images\lgl60 (279).png
[[0. 1.]]
Dat

[[0. 1.]]
DataSet\Test Images\lgl60 (60).png
[[0. 1.]]
DataSet\Test Images\lgl60 (61).png
[[0. 1.]]
DataSet\Test Images\lgl60 (62).png
[[1. 0.]]
DataSet\Test Images\lgl60 (63).png
[[0. 1.]]
DataSet\Test Images\lgl60 (64).png
[[0. 1.]]
DataSet\Test Images\lgl60 (65).png
[[0. 1.]]
DataSet\Test Images\lgl60 (66).png
[[0. 1.]]
DataSet\Test Images\lgl60 (67).png
[[0. 1.]]
DataSet\Test Images\lgl60 (68).png
[[0. 1.]]
DataSet\Test Images\lgl60 (69).png
[[0. 1.]]
DataSet\Test Images\lgl60 (7).png
[[0. 1.]]
DataSet\Test Images\lgl60 (70).png
[[0. 1.]]
DataSet\Test Images\lgl60 (71).png
[[0. 1.]]
DataSet\Test Images\lgl60 (72).png
[[0. 1.]]
DataSet\Test Images\lgl60 (73).png
[[0. 1.]]
DataSet\Test Images\lgl60 (74).png
[[0. 1.]]
DataSet\Test Images\lgl60 (75).png
[[0. 1.]]
DataSet\Test Images\lgl60 (76).png
[[0. 1.]]
DataSet\Test Images\lgl60 (77).png
[[0. 1.]]
DataSet\Test Images\lgl60 (78).png
[[0. 1.]]
DataSet\Test Images\lgl60 (79).png
[[1. 0.]]
DataSet\Test Images\lgl60 (8).png
[[0. 1.]]
Da

[[0. 1.]]
DataSet\Test Images\lgl85 (221).png
[[0. 1.]]
DataSet\Test Images\lgl85 (222).png
[[0. 1.]]
DataSet\Test Images\lgl85 (223).png
[[0. 1.]]
DataSet\Test Images\lgl85 (224).png
[[0. 1.]]
DataSet\Test Images\lgl85 (225).png
[[0. 1.]]
DataSet\Test Images\lgl85 (226).png
[[0. 1.]]
DataSet\Test Images\lgl85 (227).png
[[0. 1.]]
DataSet\Test Images\lgl85 (228).png
[[0. 1.]]
DataSet\Test Images\lgl85 (229).png
[[0. 1.]]
DataSet\Test Images\lgl85 (23).png
[[0. 1.]]
DataSet\Test Images\lgl85 (230).png
[[1. 0.]]
DataSet\Test Images\lgl85 (231).png
[[0. 1.]]
DataSet\Test Images\lgl85 (232).png
[[0. 1.]]
DataSet\Test Images\lgl85 (233).png
[[0. 1.]]
DataSet\Test Images\lgl85 (234).png
[[0. 1.]]
DataSet\Test Images\lgl85 (235).png
[[0. 1.]]
DataSet\Test Images\lgl85 (236).png
[[0. 1.]]
DataSet\Test Images\lgl85 (237).png
[[0. 1.]]
DataSet\Test Images\lgl85 (238).png
[[0. 1.]]
DataSet\Test Images\lgl85 (239).png
[[0. 1.]]
DataSet\Test Images\lgl85 (24).png
[[0. 1.]]
DataSet\Test Images\lgl85 

[[0. 1.]]
DataSet\Test Images\lgl85 (382).png
[[1. 0.]]
DataSet\Test Images\lgl85 (383).png
[[0. 1.]]
DataSet\Test Images\lgl85 (384).png
[[0. 1.]]
DataSet\Test Images\lgl85 (385).png
[[0. 1.]]
DataSet\Test Images\lgl85 (386).png
[[1. 1.]]
DataSet\Test Images\lgl85 (387).png
[[1.5594014e-29 1.0000000e+00]]
DataSet\Test Images\lgl85 (388).png
[[0. 1.]]
DataSet\Test Images\lgl85 (389).png
[[0. 1.]]
DataSet\Test Images\lgl85 (39).png
[[1. 0.]]
DataSet\Test Images\lgl85 (390).png
[[0. 1.]]
DataSet\Test Images\lgl85 (391).png
[[0. 1.]]
DataSet\Test Images\lgl85 (392).png
[[0. 1.]]
DataSet\Test Images\lgl85 (393).png
[[0. 1.]]
DataSet\Test Images\lgl85 (394).png
[[0. 1.]]
DataSet\Test Images\lgl85 (395).png
[[0. 1.]]
DataSet\Test Images\lgl85 (396).png
[[0. 1.]]
DataSet\Test Images\lgl85 (397).png
[[1. 0.]]
DataSet\Test Images\lgl85 (398).png
[[0. 1.]]
DataSet\Test Images\lgl85 (399).png
[[0. 1.]]
DataSet\Test Images\lgl85 (4).png
[[0. 1.]]
DataSet\Test Images\lgl85 (40).png
[[0. 1.]]
DataSe

[[1. 0.]]
DataSet\Test Images\lgl85 (66).png
[[0. 1.]]
DataSet\Test Images\lgl85 (67).png
[[0. 1.]]
DataSet\Test Images\lgl85 (68).png
[[0. 1.]]
DataSet\Test Images\lgl85 (69).png
[[0. 1.]]
DataSet\Test Images\lgl85 (7).png
[[0. 1.]]
DataSet\Test Images\lgl85 (70).png
[[0. 1.]]
DataSet\Test Images\lgl85 (71).png
[[0. 1.]]
DataSet\Test Images\lgl85 (72).png
[[0. 1.]]
DataSet\Test Images\lgl85 (73).png
[[0. 1.]]
DataSet\Test Images\lgl85 (74).png
[[1. 0.]]
DataSet\Test Images\lgl85 (75).png
[[0. 1.]]
DataSet\Test Images\lgl85 (76).png
[[0. 1.]]
DataSet\Test Images\lgl85 (77).png
[[0. 1.]]
DataSet\Test Images\lgl85 (78).png
[[0. 1.]]
DataSet\Test Images\lgl85 (79).png
[[0. 1.]]
DataSet\Test Images\lgl85 (8).png
[[0. 1.]]
DataSet\Test Images\lgl85 (80).png
[[0. 1.]]
DataSet\Test Images\lgl85 (81).png
[[0. 1.]]
DataSet\Test Images\lgl85 (82).png
[[0. 1.]]
DataSet\Test Images\lgl85 (83).png
[[0. 1.]]
DataSet\Test Images\lgl85 (84).png
[[1. 0.]]
DataSet\Test Images\lgl85 (85).png
[[1. 0.]]
Da

[[1. 0.]]
DataSet\Test Images\lg101 (228).png
[[1. 0.]]
DataSet\Test Images\lg101 (229).png
[[1. 0.]]
DataSet\Test Images\lg101 (23).png
[[1. 0.]]
DataSet\Test Images\lg101 (230).png
[[1. 0.]]
DataSet\Test Images\lg101 (231).png
[[1. 0.]]
DataSet\Test Images\lg101 (232).png
[[1. 0.]]
DataSet\Test Images\lg101 (233).png
[[1. 0.]]
DataSet\Test Images\lg101 (234).png
[[1. 0.]]
DataSet\Test Images\lg101 (235).png
[[1. 0.]]
DataSet\Test Images\lg101 (236).png
[[1. 0.]]
DataSet\Test Images\lg101 (237).png
[[1. 0.]]
DataSet\Test Images\lg101 (238).png
[[1. 0.]]
DataSet\Test Images\lg101 (239).png
[[1. 0.]]
DataSet\Test Images\lg101 (24).png
[[1. 0.]]
DataSet\Test Images\lg101 (240).png
[[1. 0.]]
DataSet\Test Images\lg101 (241).png
[[1. 0.]]
DataSet\Test Images\lg101 (242).png
[[1. 0.]]
DataSet\Test Images\lg101 (243).png
[[1. 0.]]
DataSet\Test Images\lg101 (244).png
[[1. 0.]]
DataSet\Test Images\lg101 (245).png
[[1. 0.]]
DataSet\Test Images\lg101 (246).png
[[1. 0.]]
DataSet\Test Images\lg101 

[[1. 0.]]
DataSet\Test Images\lg101 (81).png
[[1. 0.]]
DataSet\Test Images\lg101 (82).png
[[1. 0.]]
DataSet\Test Images\lg101 (83).png
[[1. 0.]]
DataSet\Test Images\lg101 (84).png
[[1. 0.]]
DataSet\Test Images\lg101 (85).png
[[1. 0.]]
DataSet\Test Images\lg101 (86).png
[[1. 0.]]
DataSet\Test Images\lg101 (87).png
[[1. 0.]]
DataSet\Test Images\lg101 (88).png
[[1. 0.]]
DataSet\Test Images\lg101 (89).png
[[1. 0.]]
DataSet\Test Images\lg101 (9).png
[[1. 0.]]
DataSet\Test Images\lg101 (90).png
[[1. 0.]]
DataSet\Test Images\lg101 (91).png
[[1. 0.]]
DataSet\Test Images\lg101 (92).png
[[1. 0.]]
DataSet\Test Images\lg101 (93).png
[[1. 0.]]
DataSet\Test Images\lg101 (94).png
[[1. 0.]]
DataSet\Test Images\lg101 (95).png
[[1. 0.]]
DataSet\Test Images\lg101 (96).png
[[1. 0.]]
DataSet\Test Images\lg101 (97).png
[[1. 0.]]
DataSet\Test Images\lg101 (98).png
[[1. 0.]]
DataSet\Test Images\lg101 (99).png
[[1. 0.]]
DataSet\Test Images\lg170 (1).png
[[1. 0.]]
DataSet\Test Images\lg170 (10).png
[[1. 0.]]
Da

[[1. 0.]]
DataSet\Test Images\lg170 (242).png
[[1. 0.]]
DataSet\Test Images\lg170 (243).png
[[1. 0.]]
DataSet\Test Images\lg170 (244).png
[[1. 0.]]
DataSet\Test Images\lg170 (245).png
[[1. 0.]]
DataSet\Test Images\lg170 (246).png
[[1. 0.]]
DataSet\Test Images\lg170 (247).png
[[1. 0.]]
DataSet\Test Images\lg170 (248).png
[[1. 0.]]
DataSet\Test Images\lg170 (249).png
[[1. 0.]]
DataSet\Test Images\lg170 (25).png
[[1. 0.]]
DataSet\Test Images\lg170 (250).png
[[1. 0.]]
DataSet\Test Images\lg170 (251).png
[[1. 0.]]
DataSet\Test Images\lg170 (252).png
[[1. 0.]]
DataSet\Test Images\lg170 (253).png
[[1. 0.]]
DataSet\Test Images\lg170 (254).png
[[1. 0.]]
DataSet\Test Images\lg170 (255).png
[[1. 0.]]
DataSet\Test Images\lg170 (256).png
[[1. 0.]]
DataSet\Test Images\lg170 (257).png
[[1. 0.]]
DataSet\Test Images\lg170 (258).png
[[1. 0.]]
DataSet\Test Images\lg170 (259).png
[[1. 0.]]
DataSet\Test Images\lg170 (26).png
[[1. 0.]]
DataSet\Test Images\lg170 (260).png
[[1. 0.]]
DataSet\Test Images\lg170 

[[1. 0.]]
DataSet\Test Images\lg432 (170).png
[[1. 0.]]
DataSet\Test Images\lg432 (171).png
[[1. 0.]]
DataSet\Test Images\lg432 (172).png
[[1. 0.]]
DataSet\Test Images\lg432 (173).png
[[1. 0.]]
DataSet\Test Images\lg432 (174).png
[[1. 0.]]
DataSet\Test Images\lg432 (175).png
[[1. 0.]]
DataSet\Test Images\lg432 (176).png
[[1. 0.]]
DataSet\Test Images\lg432 (177).png
[[1. 0.]]
DataSet\Test Images\lg432 (178).png
[[1. 0.]]
DataSet\Test Images\lg432 (179).png
[[1. 0.]]
DataSet\Test Images\lg432 (18).png
[[1. 0.]]
DataSet\Test Images\lg432 (180).png
[[1. 0.]]
DataSet\Test Images\lg432 (181).png
[[1. 0.]]
DataSet\Test Images\lg432 (182).png
[[1. 0.]]
DataSet\Test Images\lg432 (183).png
[[1. 0.]]
DataSet\Test Images\lg432 (184).png
[[1. 0.]]
DataSet\Test Images\lg432 (185).png
[[1. 0.]]
DataSet\Test Images\lg432 (186).png
[[1. 0.]]
DataSet\Test Images\lg432 (187).png
[[1. 0.]]
DataSet\Test Images\lg432 (188).png
[[1. 0.]]
DataSet\Test Images\lg432 (189).png
[[1. 0.]]
DataSet\Test Images\lg432

[[1. 0.]]
DataSet\Test Images\lg432 (331).png
[[1. 0.]]
DataSet\Test Images\lg432 (332).png
[[1. 0.]]
DataSet\Test Images\lg432 (333).png
[[1. 0.]]
DataSet\Test Images\lg432 (334).png
[[1. 0.]]
DataSet\Test Images\lg432 (335).png
[[1. 0.]]
DataSet\Test Images\lg432 (336).png
[[1. 0.]]
DataSet\Test Images\lg432 (337).png
[[1. 0.]]
DataSet\Test Images\lg432 (338).png
[[1. 0.]]
DataSet\Test Images\lg432 (339).png
[[1. 0.]]
DataSet\Test Images\lg432 (34).png
[[1. 0.]]
DataSet\Test Images\lg432 (340).png
[[1. 0.]]
DataSet\Test Images\lg432 (341).png
[[1. 0.]]
DataSet\Test Images\lg432 (342).png
[[1. 0.]]
DataSet\Test Images\lg432 (343).png
[[1. 0.]]
DataSet\Test Images\lg432 (344).png
[[1. 0.]]
DataSet\Test Images\lg432 (345).png
[[1. 0.]]
DataSet\Test Images\lg432 (346).png
[[1. 0.]]
DataSet\Test Images\lg432 (347).png
[[1. 0.]]
DataSet\Test Images\lg432 (348).png
[[1. 0.]]
DataSet\Test Images\lg432 (349).png
[[1. 0.]]
DataSet\Test Images\lg432 (35).png
[[1. 0.]]
DataSet\Test Images\lg432 

[[1. 0.]]
DataSet\Test Images\lg432 (493).png
[[1. 0.]]
DataSet\Test Images\lg432 (494).png
[[1. 0.]]
DataSet\Test Images\lg432 (495).png
[[1. 0.]]
DataSet\Test Images\lg432 (496).png
[[1. 0.]]
DataSet\Test Images\lg432 (497).png
[[1. 0.]]
DataSet\Test Images\lg432 (498).png
[[1. 0.]]
DataSet\Test Images\lg432 (499).png
[[1. 0.]]
DataSet\Test Images\lg432 (5).png
[[1. 0.]]
DataSet\Test Images\lg432 (50).png
[[1. 0.]]
DataSet\Test Images\lg432 (500).png
[[1. 0.]]
DataSet\Test Images\lg432 (501).png
[[1. 0.]]
DataSet\Test Images\lg432 (502).png
[[1. 0.]]
DataSet\Test Images\lg432 (503).png
[[1. 0.]]
DataSet\Test Images\lg432 (504).png
[[1. 0.]]
DataSet\Test Images\lg432 (505).png
[[1. 0.]]
DataSet\Test Images\lg432 (506).png
[[1. 0.]]
DataSet\Test Images\lg432 (507).png
[[1. 0.]]
DataSet\Test Images\lg432 (508).png
[[1. 1.]]
DataSet\Test Images\lg432 (509).png
[[1. 0.]]
DataSet\Test Images\lg432 (51).png
[[1. 0.]]
DataSet\Test Images\lg432 (510).png
[[1. 0.]]
DataSet\Test Images\lg432 (5

[[1. 0.]]
DataSet\Test Images\lg45 (179).png
[[1. 0.]]
DataSet\Test Images\lg45 (18).png
[[1. 0.]]
DataSet\Test Images\lg45 (180).png
[[1. 0.]]
DataSet\Test Images\lg45 (181).png
[[1. 0.]]
DataSet\Test Images\lg45 (182).png
[[1. 0.]]
DataSet\Test Images\lg45 (183).png
[[1. 0.]]
DataSet\Test Images\lg45 (184).png
[[1. 0.]]
DataSet\Test Images\lg45 (185).png
[[1. 0.]]
DataSet\Test Images\lg45 (186).png
[[1. 0.]]
DataSet\Test Images\lg45 (187).png
[[1. 0.]]
DataSet\Test Images\lg45 (188).png
[[1. 0.]]
DataSet\Test Images\lg45 (189).png
[[1. 0.]]
DataSet\Test Images\lg45 (19).png
[[1. 0.]]
DataSet\Test Images\lg45 (190).png
[[1. 0.]]
DataSet\Test Images\lg45 (191).png
[[1. 0.]]
DataSet\Test Images\lg45 (192).png
[[1. 0.]]
DataSet\Test Images\lg45 (193).png
[[1. 0.]]
DataSet\Test Images\lg45 (194).png
[[1. 0.]]
DataSet\Test Images\lg45 (195).png
[[1. 0.]]
DataSet\Test Images\lg45 (196).png
[[1. 0.]]
DataSet\Test Images\lg45 (197).png
[[1. 0.]]
DataSet\Test Images\lg45 (198).png
[[1. 0.]]
Da

[[1. 0.]]
DataSet\Test Images\lg45 (343).png
[[1. 0.]]
DataSet\Test Images\lg45 (344).png
[[1. 0.]]
DataSet\Test Images\lg45 (345).png
[[1. 0.]]
DataSet\Test Images\lg45 (346).png
[[1. 0.]]
DataSet\Test Images\lg45 (347).png
[[1. 0.]]
DataSet\Test Images\lg45 (348).png
[[1. 0.]]
DataSet\Test Images\lg45 (349).png
[[1. 0.]]
DataSet\Test Images\lg45 (35).png
[[1. 0.]]
DataSet\Test Images\lg45 (350).png
[[1. 0.]]
DataSet\Test Images\lg45 (351).png
[[1. 0.]]
DataSet\Test Images\lg45 (352).png
[[1. 0.]]
DataSet\Test Images\lg45 (353).png
[[1. 0.]]
DataSet\Test Images\lg45 (354).png
[[1. 0.]]
DataSet\Test Images\lg45 (355).png
[[1. 0.]]
DataSet\Test Images\lg45 (356).png
[[1. 0.]]
DataSet\Test Images\lg45 (357).png
[[1. 0.]]
DataSet\Test Images\lg45 (358).png
[[1. 0.]]
DataSet\Test Images\lg45 (359).png
[[1. 0.]]
DataSet\Test Images\lg45 (36).png
[[1. 0.]]
DataSet\Test Images\lg45 (360).png
[[1. 0.]]
DataSet\Test Images\lg45 (361).png
[[1. 0.]]
DataSet\Test Images\lg45 (362).png
[[1. 0.]]
Da

[[1. 0.]]
DataSet\Test Images\lg45 (508).png
[[1. 0.]]
DataSet\Test Images\lg45 (509).png
[[1. 0.]]
DataSet\Test Images\lg45 (51).png
[[1. 0.]]
DataSet\Test Images\lg45 (510).png
[[1. 0.]]
DataSet\Test Images\lg45 (511).png
[[1. 0.]]
DataSet\Test Images\lg45 (512).png
[[1. 0.]]
DataSet\Test Images\lg45 (513).png
[[1. 0.]]
DataSet\Test Images\lg45 (514).png
[[1. 0.]]
DataSet\Test Images\lg45 (515).png
[[1. 0.]]
DataSet\Test Images\lg45 (516).png
[[1. 0.]]
DataSet\Test Images\lg45 (517).png
[[1. 0.]]
DataSet\Test Images\lg45 (518).png
[[1. 0.]]
DataSet\Test Images\lg45 (519).png
[[1. 0.]]
DataSet\Test Images\lg45 (52).png
[[1. 0.]]
DataSet\Test Images\lg45 (520).png
[[1. 0.]]
DataSet\Test Images\lg45 (521).png
[[1. 0.]]
DataSet\Test Images\lg45 (522).png
[[1. 0.]]
DataSet\Test Images\lg45 (523).png
[[1. 0.]]
DataSet\Test Images\lg45 (524).png
[[1. 0.]]
DataSet\Test Images\lg45 (525).png
[[1. 0.]]
DataSet\Test Images\lg45 (526).png
[[1. 0.]]
DataSet\Test Images\lg45 (527).png
[[1. 0.]]
Da

[[1. 0.]]
DataSet\Test Images\lg56 (18).png
[[1. 0.]]
DataSet\Test Images\lg56 (180).png
[[1. 0.]]
DataSet\Test Images\lg56 (181).png
[[1. 0.]]
DataSet\Test Images\lg56 (182).png
[[1. 0.]]
DataSet\Test Images\lg56 (183).png
[[1. 0.]]
DataSet\Test Images\lg56 (184).png
[[1. 0.]]
DataSet\Test Images\lg56 (185).png
[[1. 0.]]
DataSet\Test Images\lg56 (186).png
[[1. 0.]]
DataSet\Test Images\lg56 (187).png
[[1. 0.]]
DataSet\Test Images\lg56 (188).png
[[1. 0.]]
DataSet\Test Images\lg56 (189).png
[[1. 0.]]
DataSet\Test Images\lg56 (19).png
[[1. 0.]]
DataSet\Test Images\lg56 (190).png
[[1. 0.]]
DataSet\Test Images\lg56 (191).png
[[1. 0.]]
DataSet\Test Images\lg56 (192).png
[[1. 0.]]
DataSet\Test Images\lg56 (193).png
[[1. 0.]]
DataSet\Test Images\lg56 (194).png
[[1. 0.]]
DataSet\Test Images\lg56 (195).png
[[1. 0.]]
DataSet\Test Images\lg56 (196).png
[[1. 0.]]
DataSet\Test Images\lg56 (197).png
[[1. 0.]]
DataSet\Test Images\lg56 (198).png
[[1. 0.]]
DataSet\Test Images\lg56 (199).png
[[1. 0.]]
Da

[[1. 0.]]
DataSet\Test Images\lg56 (78).png
[[1. 0.]]
DataSet\Test Images\lg56 (79).png
[[1. 0.]]
DataSet\Test Images\lg56 (8).png
[[1. 0.]]
DataSet\Test Images\lg56 (80).png
[[1. 0.]]
DataSet\Test Images\lg56 (81).png
[[1. 0.]]
DataSet\Test Images\lg56 (82).png
[[1. 0.]]
DataSet\Test Images\lg56 (83).png
[[1. 0.]]
DataSet\Test Images\lg56 (84).png
[[1. 1.]]
DataSet\Test Images\lg56 (85).png
[[1. 0.]]
DataSet\Test Images\lg56 (86).png
[[1. 0.]]
DataSet\Test Images\lg56 (87).png
[[1. 0.]]
DataSet\Test Images\lg56 (88).png
[[1. 0.]]
DataSet\Test Images\lg56 (89).png
[[1. 0.]]
DataSet\Test Images\lg56 (9).png
[[1. 0.]]
DataSet\Test Images\lg56 (90).png
[[1. 0.]]
DataSet\Test Images\lg56 (91).png
[[1. 0.]]
DataSet\Test Images\lg56 (92).png
[[1. 0.]]
DataSet\Test Images\lg56 (93).png
[[1. 0.]]
DataSet\Test Images\lg56 (94).png
[[0. 1.]]
DataSet\Test Images\lg56 (95).png
[[1. 0.]]
DataSet\Test Images\lg56 (96).png
[[1. 0.]]
DataSet\Test Images\lg56 (97).png
[[1. 0.]]
DataSet\Test Images\lg56

[[1. 0.]]
DataSet\Test Images\lg566 (24).png
[[1. 0.]]
DataSet\Test Images\lg566 (240).png
[[1. 0.]]
DataSet\Test Images\lg566 (241).png
[[1. 0.]]
DataSet\Test Images\lg566 (242).png
[[1. 0.]]
DataSet\Test Images\lg566 (243).png
[[1. 0.]]
DataSet\Test Images\lg566 (244).png
[[1. 0.]]
DataSet\Test Images\lg566 (245).png
[[1. 0.]]
DataSet\Test Images\lg566 (246).png
[[1. 0.]]
DataSet\Test Images\lg566 (247).png
[[1. 0.]]
DataSet\Test Images\lg566 (248).png
[[1. 0.]]
DataSet\Test Images\lg566 (249).png
[[1. 0.]]
DataSet\Test Images\lg566 (25).png
[[1. 0.]]
DataSet\Test Images\lg566 (250).png
[[1. 0.]]
DataSet\Test Images\lg566 (251).png
[[1. 0.]]
DataSet\Test Images\lg566 (252).png
[[1. 0.]]
DataSet\Test Images\lg566 (253).png
[[1. 0.]]
DataSet\Test Images\lg566 (254).png
[[1. 0.]]
DataSet\Test Images\lg566 (255).png
[[1. 0.]]
DataSet\Test Images\lg566 (256).png
[[1. 0.]]
DataSet\Test Images\lg566 (257).png
[[1. 0.]]
DataSet\Test Images\lg566 (258).png
[[1. 0.]]
DataSet\Test Images\lg566 

[[1. 0.]]
DataSet\Test Images\lg566 (400).png
[[1. 0.]]
DataSet\Test Images\lg566 (401).png
[[1. 0.]]
DataSet\Test Images\lg566 (402).png
[[1. 0.]]
DataSet\Test Images\lg566 (403).png
[[1. 0.]]
DataSet\Test Images\lg566 (404).png
[[1. 0.]]
DataSet\Test Images\lg566 (405).png
[[1. 1.]]
DataSet\Test Images\lg566 (406).png
[[1. 0.]]
DataSet\Test Images\lg566 (407).png
[[1. 0.]]
DataSet\Test Images\lg566 (408).png
[[1. 0.]]
DataSet\Test Images\lg566 (409).png
[[1. 0.]]
DataSet\Test Images\lg566 (41).png
[[1. 0.]]
DataSet\Test Images\lg566 (410).png
[[1. 0.]]
DataSet\Test Images\lg566 (411).png
[[1. 0.]]
DataSet\Test Images\lg566 (412).png
[[1. 0.]]
DataSet\Test Images\lg566 (413).png
[[1. 0.]]
DataSet\Test Images\lg566 (414).png
[[1. 0.]]
DataSet\Test Images\lg566 (415).png
[[1. 0.]]
DataSet\Test Images\lg566 (416).png
[[1. 0.]]
DataSet\Test Images\lg566 (417).png
[[1. 0.]]
DataSet\Test Images\lg566 (418).png
[[1. 0.]]
DataSet\Test Images\lg566 (419).png
[[1. 0.]]
DataSet\Test Images\lg566

[[1. 0.]]
DataSet\Test Images\lg76 (145).png
[[1. 0.]]
DataSet\Test Images\lg76 (146).png
[[1. 0.]]
DataSet\Test Images\lg76 (147).png
[[1. 0.]]
DataSet\Test Images\lg76 (148).png
[[1. 0.]]
DataSet\Test Images\lg76 (149).png
[[1. 0.]]
DataSet\Test Images\lg76 (15).png
[[1. 0.]]
DataSet\Test Images\lg76 (150).png
[[1. 0.]]
DataSet\Test Images\lg76 (151).png
[[1. 0.]]
DataSet\Test Images\lg76 (152).png
[[1. 0.]]
DataSet\Test Images\lg76 (153).png
[[1. 0.]]
DataSet\Test Images\lg76 (154).png
[[1. 0.]]
DataSet\Test Images\lg76 (155).png
[[1. 0.]]
DataSet\Test Images\lg76 (156).png
[[1. 0.]]
DataSet\Test Images\lg76 (157).png
[[1. 0.]]
DataSet\Test Images\lg76 (158).png
[[1. 0.]]
DataSet\Test Images\lg76 (159).png
[[1. 0.]]
DataSet\Test Images\lg76 (16).png
[[1. 0.]]
DataSet\Test Images\lg76 (160).png
[[1. 0.]]
DataSet\Test Images\lg76 (161).png
[[1. 0.]]
DataSet\Test Images\lg76 (162).png
[[1. 0.]]
DataSet\Test Images\lg76 (163).png
[[1. 0.]]
DataSet\Test Images\lg76 (164).png
[[1. 0.]]
Da

[[1. 0.]]
DataSet\Test Images\lg87 (141).png
[[1. 0.]]
DataSet\Test Images\lg87 (142).png
[[1. 0.]]
DataSet\Test Images\lg87 (143).png
[[1. 0.]]
DataSet\Test Images\lg87 (144).png
[[1. 0.]]
DataSet\Test Images\lg87 (145).png
[[1. 0.]]
DataSet\Test Images\lg87 (146).png
[[1. 0.]]
DataSet\Test Images\lg87 (147).png
[[1. 0.]]
DataSet\Test Images\lg87 (148).png
[[1. 0.]]
DataSet\Test Images\lg87 (149).png
[[1. 0.]]
DataSet\Test Images\lg87 (15).png
[[1. 0.]]
DataSet\Test Images\lg87 (150).png
[[1. 0.]]
DataSet\Test Images\lg87 (151).png
[[1. 0.]]
DataSet\Test Images\lg87 (152).png
[[1. 0.]]
DataSet\Test Images\lg87 (153).png
[[1. 0.]]
DataSet\Test Images\lg87 (154).png
[[1. 0.]]
DataSet\Test Images\lg87 (155).png
[[1. 0.]]
DataSet\Test Images\lg87 (156).png
[[1. 0.]]
DataSet\Test Images\lg87 (157).png
[[1. 0.]]
DataSet\Test Images\lg87 (158).png
[[1. 0.]]
DataSet\Test Images\lg87 (159).png
[[1. 0.]]
DataSet\Test Images\lg87 (16).png
[[1. 0.]]
DataSet\Test Images\lg87 (160).png
[[1. 0.]]
Da

[[1. 0.]]
DataSet\Test Images\lg87 (305).png
[[1. 0.]]
DataSet\Test Images\lg87 (306).png
[[1. 0.]]
DataSet\Test Images\lg87 (307).png
[[1. 0.]]
DataSet\Test Images\lg87 (308).png
[[1. 0.]]
DataSet\Test Images\lg87 (309).png
[[1. 0.]]
DataSet\Test Images\lg87 (31).png
[[1. 0.]]
DataSet\Test Images\lg87 (310).png
[[1. 0.]]
DataSet\Test Images\lg87 (311).png
[[1. 0.]]
DataSet\Test Images\lg87 (312).png
[[1. 0.]]
DataSet\Test Images\lg87 (313).png
[[1. 0.]]
DataSet\Test Images\lg87 (314).png
[[1. 0.]]
DataSet\Test Images\lg87 (315).png
[[1. 0.]]
DataSet\Test Images\lg87 (316).png
[[0. 1.]]
DataSet\Test Images\lg87 (317).png
[[1. 0.]]
DataSet\Test Images\lg87 (318).png
[[1. 0.]]
DataSet\Test Images\lg87 (319).png
[[1. 0.]]
DataSet\Test Images\lg87 (32).png
[[1. 0.]]
DataSet\Test Images\lg87 (320).png
[[1. 0.]]
DataSet\Test Images\lg87 (321).png
[[1. 0.]]
DataSet\Test Images\lg87 (322).png
[[1. 0.]]
DataSet\Test Images\lg87 (323).png
[[1. 0.]]
DataSet\Test Images\lg87 (324).png
[[1. 0.]]
Da

[[1. 0.]]
DataSet\Test Images\lg87 (49).png
[[1. 0.]]
DataSet\Test Images\lg87 (5).png
[[1. 0.]]
DataSet\Test Images\lg87 (50).png
[[1. 0.]]
DataSet\Test Images\lg87 (51).png
[[1. 0.]]
DataSet\Test Images\lg87 (52).png
[[1. 0.]]
DataSet\Test Images\lg87 (53).png
[[1. 0.]]
DataSet\Test Images\lg87 (54).png
[[1. 0.]]
DataSet\Test Images\lg87 (55).png
[[1. 0.]]
DataSet\Test Images\lg87 (56).png
[[1. 0.]]
DataSet\Test Images\lg87 (57).png
[[1. 0.]]
DataSet\Test Images\lg87 (58).png
[[1. 0.]]
DataSet\Test Images\lg87 (59).png
[[1. 0.]]
DataSet\Test Images\lg87 (6).png
[[1. 0.]]
DataSet\Test Images\lg87 (60).png
[[1. 0.]]
DataSet\Test Images\lg87 (61).png
[[1. 0.]]
DataSet\Test Images\lg87 (62).png
[[1. 0.]]
DataSet\Test Images\lg87 (63).png
[[1. 0.]]
DataSet\Test Images\lg87 (64).png
[[0. 1.]]
DataSet\Test Images\lg87 (65).png
[[1. 0.]]
DataSet\Test Images\lg87 (66).png
[[1. 0.]]
DataSet\Test Images\lg87 (67).png
[[1. 0.]]
DataSet\Test Images\lg87 (68).png
[[1. 0.]]
DataSet\Test Images\lg87

[[1. 0.]]
DataSet\Test Images\lg898 (211).png
[[1. 0.]]
DataSet\Test Images\lg898 (212).png
[[1. 0.]]
DataSet\Test Images\lg898 (213).png
[[1. 0.]]
DataSet\Test Images\lg898 (214).png
[[1. 0.]]
DataSet\Test Images\lg898 (215).png
[[1. 0.]]
DataSet\Test Images\lg898 (216).png
[[1. 0.]]
DataSet\Test Images\lg898 (217).png
[[1. 0.]]
DataSet\Test Images\lg898 (218).png
[[1. 0.]]
DataSet\Test Images\lg898 (219).png
[[1. 0.]]
DataSet\Test Images\lg898 (22).png
[[1. 0.]]
DataSet\Test Images\lg898 (220).png
[[1. 0.]]
DataSet\Test Images\lg898 (221).png
[[1. 0.]]
DataSet\Test Images\lg898 (222).png
[[1. 0.]]
DataSet\Test Images\lg898 (223).png
[[1. 0.]]
DataSet\Test Images\lg898 (224).png
[[1. 0.]]
DataSet\Test Images\lg898 (225).png
[[1. 0.]]
DataSet\Test Images\lg898 (226).png
[[1. 0.]]
DataSet\Test Images\lg898 (227).png
[[1. 0.]]
DataSet\Test Images\lg898 (228).png
[[1. 0.]]
DataSet\Test Images\lg898 (229).png
[[1. 0.]]
DataSet\Test Images\lg898 (23).png
[[1. 0.]]
DataSet\Test Images\lg898 

[[1. 0.]]
DataSet\Test Images\lg898 (57).png
[[1. 0.]]
DataSet\Test Images\lg898 (58).png
[[1. 0.]]
DataSet\Test Images\lg898 (59).png
[[1. 0.]]
DataSet\Test Images\lg898 (6).png
[[1. 0.]]
DataSet\Test Images\lg898 (60).png
[[1. 0.]]
DataSet\Test Images\lg898 (61).png
[[1. 0.]]
DataSet\Test Images\lg898 (62).png
[[1. 0.]]
DataSet\Test Images\lg898 (63).png
[[1. 0.]]
DataSet\Test Images\lg898 (64).png
[[1. 0.]]
DataSet\Test Images\lg898 (65).png
[[1. 0.]]
DataSet\Test Images\lg898 (66).png
[[1. 0.]]
DataSet\Test Images\lg898 (67).png
[[1. 0.]]
DataSet\Test Images\lg898 (68).png
[[1. 0.]]
DataSet\Test Images\lg898 (69).png
[[1. 0.]]
DataSet\Test Images\lg898 (7).png
[[1. 0.]]
DataSet\Test Images\lg898 (70).png
[[1. 0.]]
DataSet\Test Images\lg898 (71).png
[[1. 0.]]
DataSet\Test Images\lg898 (72).png
[[1. 0.]]
DataSet\Test Images\lg898 (73).png
[[1. 0.]]
DataSet\Test Images\lg898 (74).png
[[1. 0.]]
DataSet\Test Images\lg898 (75).png
[[1. 0.]]
DataSet\Test Images\lg898 (76).png
[[0. 1.]]
Da

[[1. 0.]]
DataSet\Test Images\lg99 (221).png
[[1. 0.]]
DataSet\Test Images\lg99 (222).png
[[1. 0.]]
DataSet\Test Images\lg99 (223).png
[[1. 0.]]
DataSet\Test Images\lg99 (224).png
[[1. 0.]]
DataSet\Test Images\lg99 (225).png
[[1. 0.]]
DataSet\Test Images\lg99 (226).png
[[1. 0.]]
DataSet\Test Images\lg99 (227).png
[[1. 0.]]
DataSet\Test Images\lg99 (228).png
[[1. 0.]]
DataSet\Test Images\lg99 (229).png
[[1. 0.]]
DataSet\Test Images\lg99 (23).png
[[1. 0.]]
DataSet\Test Images\lg99 (230).png
[[1. 0.]]
DataSet\Test Images\lg99 (231).png
[[1. 0.]]
DataSet\Test Images\lg99 (232).png
[[1. 0.]]
DataSet\Test Images\lg99 (233).png
[[1. 0.]]
DataSet\Test Images\lg99 (234).png
[[1. 0.]]
DataSet\Test Images\lg99 (235).png
[[1. 0.]]
DataSet\Test Images\lg99 (236).png
[[1. 0.]]
DataSet\Test Images\lg99 (237).png
[[1. 0.]]
DataSet\Test Images\lg99 (238).png
[[1. 0.]]
DataSet\Test Images\lg99 (239).png
[[1. 0.]]
DataSet\Test Images\lg99 (24).png
[[1. 0.]]
DataSet\Test Images\lg99 (240).png
[[1. 0.]]
Da

# saving modified dataframe in csv format.

In [106]:
names.to_csv("result.csv",index = False)